# GitHub Action: https://dev.to/leoloso/using-github-actions-to-release-a-wordpress-plugin-42a5

name: Generate Installable Plugin, and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'wooms.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig .github tests'
